export { nouns } from './nouns.js'
export { adverbs } from './adverbs.js'
export { verbs } from './verbs.js'
export { interjections } from './interjections.js'
export { adjectives } from './adjectives.js'
